name: Update test case status to Jira
on:
  push:
    branches:
      - main
      - cicd
env:
  CACHE_KEY: node-deps
  JIRA_BASE_URL: https://huynh-thong-duong-se183537.atlassian.net
  JIRA_PROJECT_KEY: N3NJS1804
defaults:
  run:
    working-directory: CODING/FE
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
        with:
          sparse-checkout: CODING/FE
          sparse-checkout-cone-mode: false
      - name: Output information
        run: ls
      - name: Cache deps
        id: cache
        uses: actions/cache@v4.0.2
        with:
          key: node_modules
          path: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test
        run: npm run test
      - name: Extract Jira Issue Key from Commit Message
        id: extract
        run: |
          commit_message=$(git log -1 --pretty=%B)
          echo "Commit message: $commit_message" 
          if [[ "$commit_message" =~ (${{ env.JIRA_PROJECT_KEY }}-[0-9]+):(.*)$ ]]
          then
            echo "Jira Issue Key: ${BASH_REMATCH[1]}"
            echo "JIRA_ISSUE_KEY=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
            echo "JIRA_ISSUE_DESCRIPTION=${BASH_REMATCH[2]}" >> $GITHUB_OUTPUT
          else
            echo "No Jira Issue Key found in commit message"
            exit 1
            fi
      - name: Create data.json for Jira Update if success
        continue-on-error: true
        run: |
          echo '{ "transition": { "id": "11" }, "fields": { "customfield_10037": "Pass", "description": "${{ steps.extract.outputs.JIRA_ISSUE_DESCRIPTION }}" } }' > data.json
      - name: Create data.json for Jira Update if failure
        if: failure() && steps.extract.outcome != 'success'
        run: |
          echo '{ "transition": { "id": "11" }, "fields": { "issuetype": { "id": "10009" }, "customfield_10037": "Fail", "description": "${{ steps.extract.outputs.JIRA_ISSUE_DESCRIPTION }}" } }' > data.json
      - name: Update Jira
        run: |
          curl -D- -u ${{ secrets.JIRA_USERNAME }}:${{ secrets.JIRA_API_TOKEN }} -X POST --data @data.json -H "Content-Type: application/json" ${{ env.JIRA_BASE_URL }}/rest/api/2/issue/${{ steps.extract.outputs.JIRA_ISSUE_KEY }}/transitions
